### ISSUE TITLE
ForegroundNotification module on OOS 14 (OnePlus 11)

### ISSUE THREAD

**Issue by binarynoise** [binarynoise/XposedModulets#8]
> @binarynoise @IzzySoft - I tried the ForegroundNotification module on OOS 14 (OnePlus 11) and it doesn't seem to work. Any leads on this please?

_Originally posted by @cooldroid in https://github.com/binarynoise/XposedModulets/issues/6#issuecomment-2278301440_

**Comment by binarynoise** [comment]
@cooldroid, please share the logs from LSPosed, so I have a stacktrace to work with

**Comment by cooldroid** [comment]
[LSPosed_2024-08-15T00_16_49.536290.zip](https://github.com/user-attachments/files/16617687/LSPosed_2024-08-15T00_16_49.536290.zip)
Attached is the logs from LSPosed

**Comment by binarynoise** [comment]
Can you try this version?
[PersistentForegroundServiceNotifications-debug.apk.zip](https://github.com/user-attachments/files/16638317/PersistentForegroundServiceNotifications-debug.apk.zip)
To install, remove the `.zip` from the filename.
It won't fix it but it includes more logging.

**Comment by cooldroid** [comment]
[verbose_2024-08-16T21_38_24.627404.log](https://github.com/user-attachments/files/16639201/verbose_2024-08-16T21_38_24.627404.log)
Here is the verbose log from LSPosed.

**Comment by binarynoise** [comment]
Interesting, none of the notifications are either marked as `foregroundService` or `noDismiss`, only as `ongoingEvent` and `noClear`.
However, I don't check for those flags as they include too many notifications (ongoing events that don't come from services) or for a different use case.
It looks like OOS did some modification to the behaviour of foreground service notifications that break the expectation that they are flagged as such.
Unfortunately I don't own an OOS device and I guess it wouldn't be worth it for you to buy me one, so I cannot debug that.

**Comment by binarynoise** [comment]
Interesting, none of the notifications are either marked as `foregroundService` or `noDismiss`, only as `ongoingEvent` and `noClear`.
However, I don't check for those flags as they include too many notifications (ongoing events that don't come from services) or for a different use case.
It looks like OOS did some modification to the behaviour of foreground service notifications that break the expectation that they are flagged as such.
Unfortunately I don't own an OOS device and I guess it wouldn't be worth it for you to buy me one, so I cannot debug that.

I created a variant that also checks the `ongoingEvent` flag, please report if you get false positives.
[PersistentForegroundServiceNotifications-isOngoing-release.apk.zip](https://github.com/user-attachments/files/16640419/PersistentForegroundServiceNotifications-isOngoing-release.apk.zip)

**Comment by cooldroid** [comment]
> Interesting, none of the notifications are either marked as `foregroundService` or `noDismiss`, only as `ongoingEvent` and `noClear`. However, I don't check for those flags as they include too many notifications (ongoing events that don't come from services) or for a different use case. It looks like OOS did some modification to the behaviour of foreground service notifications that break the expectation that they are flagged as such. Unfortunately I don't own an OOS device and I guess it wouldn't be worth it for you to buy me one, so I cannot debug that.
> 
> I created a variant that also checks the `ongoingEvent` flag, please report if you get false positives. [PersistentForegroundServiceNotifications-isOngoing-release.apk.zip](https://github.com/user-attachments/files/16640419/PersistentForegroundServiceNotifications-isOngoing-release.apk.zip)

This works well so far (no false positives yet for me).

Thanks a lot for looking in this and see it to resolution.

**Comment by cooldroid** [comment]
@binarynoise, on a separate context, can you guide where to start looking, for hiding the silent notification's icon on the status bar. Again, this issue is very specific to OnePlus OOS. I have basic idea in development, so if you point me on where can I start looking (maybe within SystemUI), it'll help a lot. This link can give some context issue and a workaround is also suggested, but it doesn't persist across reboot, hence, looking for an Xposed solution.

https://www.reddit.com/r/oneplus/s/1zto50DO7A

**Comment by binarynoise** [comment]
Yeah, that will be somewhere in SystemUI where the status bar is rendered.
Here is the general android source code, that could be a starting point for your further research: <https://cs.android.com/android>, however OOS doesn't look open source so you might need to reverse engineer the SystemUI you have on your phone with [JADX](https://github.com/skylot/jadx)

**Comment by cooldroid** [comment]
As you suggested I reverse engineered the SystemUI apk and was able to resolve the issue. BTW, do you mind if I share my changes with other OnePlus users facing the same issue?

**Comment by binarynoise** [comment]
1. How did you resolve the issue?
2. You found it on your own, share your knowledge as you like.

**Comment by cooldroid** [comment]
The issue was that OnePlus has their own Notification controller i.e. "OplusNotificationIconAreaController", which controls the display of notification icons. I had to hook the method "getShowLowPriority" to fix the issue.
