### ISSUE TITLE
FreeNotifications doesn't work on OOS/COS

### ISSUE THREAD

**Issue by Xynonners** [binarynoise/XposedModulets#9]
verbose logs don't seem to indicate something is wrong, but the notification sliders of SystemUI are still greyed out.

**Comment by binarynoise** [comment]
Please share the verbose logs with me then.

**Comment by Xynonners** [comment]
> Please share the verbose logs with me then.

here are the logs.

[LSPosed_2024-10-05T07_23_33.882353.zip](https://github.com/user-attachments/files/17266533/LSPosed_2024-10-05T07_23_33.882353.zip)

**Comment by binarynoise** [comment]
[FreeNotifications-debug.apk.zip](https://github.com/user-attachments/files/17266851/FreeNotifications-debug.apk.zip)
Here is a debug apk (just remove the .zip after downloading) with logging.
It looks like the module doesn't find anything to hook and just skips it.

**Comment by Xynonners** [comment]
> [FreeNotifications-debug.apk.zip](https://github.com/user-attachments/files/17266851/FreeNotifications-debug.apk.zip) Here is a debug apk (just remove the .zip after downloading) with logging. It looks like the module doesn't find anything to hook and just skips it.

[LSPosed_2024-10-05T20_26_34.285136.zip](https://github.com/user-attachments/files/17268001/LSPosed_2024-10-05T20_26_34.285136.zip)

still looks like nothing is happening?

**Comment by binarynoise** [comment]
Yeah, the build only added logging.
Unfortunately, the LSPosed logs don't seem to contain the logcat output of my module, can you capture a logcat for `FreeNotifications`? Or do you want an apk that makes logs appear in the lsposed logs?

**Comment by binarynoise** [comment]
[FreeNotifications-debug.apk.zip](https://github.com/user-attachments/files/17291209/FreeNotifications-debug.apk.zip)
Here the log messages should go into the LSPosed logs.

To use logcat instead, the command should be `adb logcat FreeNotifications:D`

**Comment by Xynonners** [comment]
I did logcat freeNotifications:* *:S, here is the output

```
--------- beginning of main
[ 10-08 08:17:05.987  3142: 3142 I/FreeNotifications ]
hooked constructors: 2

[ 10-08 08:17:05.987  3142: 3142 I/FreeNotifications ]
hooked setBlockable

[ 10-08 08:17:05.988  3142: 3142 I/FreeNotifications ]
hooked isBlockable

[ 10-08 08:17:07.945  3142: 3142 I/FreeNotifications ]
hooked constructors: 2

[ 10-08 08:17:07.945  3142: 3142 I/FreeNotifications ]
hooked setBlockable

[ 10-08 08:17:07.945  3142: 3142 I/FreeNotifications ]
hooked isBlockable

[ 10-08 08:17:08.021  3142: 3142 I/FreeNotifications ]
hooked constructors: 2

[ 10-08 08:17:08.021  3142: 3142 I/FreeNotifications ]
hooked setBlockable

[ 10-08 08:17:08.021  3142: 3142 I/FreeNotifications ]
hooked isBlockable

[ 10-08 08:17:08.038  3142: 3142 I/FreeNotifications ]
hooked constructors: 2

[ 10-08 08:17:08.038  3142: 3142 I/FreeNotifications ]
hooked setBlockable

[ 10-08 08:17:08.038  3142: 3142 I/FreeNotifications ]
hooked isBlockable

[ 10-08 08:17:08.104  3142: 3142 I/FreeNotifications ]
hooked constructors: 2

[ 10-08 08:17:08.104  3142: 3142 I/FreeNotifications ]
hooked setBlockable

[ 10-08 08:17:08.104  3142: 3142 I/FreeNotifications ]
hooked isBlockable

[ 10-08 08:17:09.860  4712: 4712 I/FreeNotifications ]
hooked constructors: 2

[ 10-08 08:17:09.867  4712: 4712 I/FreeNotifications ]
hooked setBlockable

[ 10-08 08:17:09.867  4712: 4712 I/FreeNotifications ]
hooked isBlockable

[ 10-08 08:17:11.370  3142: 3142 I/FreeNotifications ]
hooked constructors: 2

[ 10-08 08:17:11.370  3142: 3142 I/FreeNotifications ]
hooked setBlockable

[ 10-08 08:17:11.370  3142: 3142 I/FreeNotifications ]
hooked isBlockable

[ 10-08 08:17:11.386  3142: 3142 I/FreeNotifications ]
hooked constructors: 2

[ 10-08 08:17:11.386  3142: 3142 I/FreeNotifications ]
hooked setBlockable

[ 10-08 08:17:11.386  3142: 3142 I/FreeNotifications ]
hooked isBlockable

[ 10-08 08:17:11.398  5120: 5120 I/FreeNotifications ]
hooked constructors: 2

[ 10-08 08:17:11.398  5120: 5120 I/FreeNotifications ]
hooked setBlockable

[ 10-08 08:17:11.399  5120: 5120 I/FreeNotifications ]
hooked isBlockable

[ 10-08 08:17:11.416  3142: 3142 I/FreeNotifications ]
hooked constructors: 2

[ 10-08 08:17:11.416  3142: 3142 I/FreeNotifications ]
hooked setBlockable

[ 10-08 08:17:11.416  3142: 3142 I/FreeNotifications ]
hooked isBlockable

[ 10-08 08:17:23.433  9004: 9004 I/FreeNotifications ]
hooked constructors: 2

[ 10-08 08:17:23.435  9004: 9004 I/FreeNotifications ]
hooked setBlockable

[ 10-08 08:17:23.435  9004: 9004 I/FreeNotifications ]
hooked isBlockable
```

**Comment by binarynoise** [comment]
That looks how it should look like.
Can you send me your `framework.jar` (in `/system/framework/`) for further analysis?

**Comment by Xynonners** [comment]
> That looks how it should look like. Can you send me your `framework.jar` (in `/system/framework/`) for further analysis?

https://mega.nz/file/6Bs3BBLT#N3H5IwNsAwSy_2nO-eDPI3ujt-07Lv0lqNRIhTPMP_A

(file too big so I put it on mega)

**Comment by binarynoise** [comment]
Also looks like it should look like. I don't know why it doesn't work for you.
One thing to check though, do you have the option to disable an unwanted notification when you long press it in the notification drawer?

**Comment by Xynonners** [comment]
> Also looks like it should look like. I don't know why it doesn't work for you. One thing to check though, do you have the option to disable an unwanted notification when you long press it in the notification drawer?

yes, but only on user notifications

on system notifications the button is replaced by "These notifications cannot be modified".

**Comment by Xynonners** [comment]
maybe it's in the other files in /system/framework?

I have oplus-framework.jar which seems to be OEM

**Comment by Xynonners** [comment]
[oplus-framework.jar.zip](https://github.com/user-attachments/files/17311869/oplus-framework.jar.zip)

**Comment by Xynonners** [comment]
> > on system notifications the button is replaced by "These notifications cannot be modified".
> 
> That means it neither works in the Settings app nor in SystemUI
> 
> > maybe it's in the other files in /system/framework?
> 
> I had a look, it does contain a related class that seems to extend NotificationChannel but it doesn't look like it modifies the isBlockable behaviour.
> 
> One last resort would be looking at SystemUI to see if they override the behaviour there

tell me the files you need and I'll get them for you

https://mega.nz/file/uBVnWIrS#5Lmw3gdcvlu6AmX7ZjRulCxdUTtL8jQtBtcqNXL7ROw

**Comment by Xynonners** [comment]
there's also this com.oplus.notificationmanager in system_ext.

[NotificationCenter.apk.zip](https://github.com/user-attachments/files/17317182/NotificationCenter.apk.zip)

**Comment by binarynoise** [comment]
In SystemUI I could see why it doesn't work. They added another property, `isImportanceLockedByCriticalDeviceFunction`, for "critical" device functions.
I'll add it this weekend or so and send you another build.

**Comment by Xynonners** [comment]
> In SystemUI I could see why it doesn't work. They added another property, `isImportanceLockedByCriticalDeviceFunction`, for "critical" device functions. I'll add it this weekend or so and send you another build.

oh okay, thanks a lot!

**Comment by binarynoise** [comment]
[FreeNotifications-debug.apk.zip](https://github.com/user-attachments/files/17357127/FreeNotifications-debug.apk.zip)
Here is a version with `importanceLockedByCriticalDeviceFunction`

**Comment by binarynoise** [comment]
I will take another look at the issue eventually, however I'm currently busy too.

**Comment by binarynoise** [comment]
Turns out, `isImportanceLockedByCriticalDeviceFunction` is AOSP, but they don't trust it (?) so they have a list of packages they block.
[FreeNotifications-debug.apk.zip](https://github.com/user-attachments/files/17787112/FreeNotifications-debug.apk.zip)
Here is a version with `mNonBlockablePkgs` cleared.

**Comment by Xynonners** [comment]
lmao, it seems they really don't want to let people turn off notifications

tried the new version and it's still grey sadly (shows allow notifications slider as greyed out, all channels greyed out and "these notifications cannot be modified" when hold-tapped on in notification drawer)

**Comment by Xynonners** [comment]
![Screenshot_2024-11-17-02-17-17-92_8142442b4340f41fb3bd44535ad8f76b](https://github.com/user-attachments/assets/8afc4d32-de0d-46b4-8b10-90a38ba98f0b)

**Comment by binarynoise** [comment]
This is the settings app. What about directly editing the notifications in the notification drawer? If that works, can you send me the settings apk so I can figure out what :hankey: they did there?
Also, can you give me the logs so I can see whether anything I added works?

**Comment by Xynonners** [comment]
> This is the settings app. What about directly editing the notifications in the notification drawer? If that works, can you send me the settings apk so I can figure out what 💩 they did there? Also, can you give me the logs so I can see whether anything I added works?

Notification drawer still "cannot modify" too :(
[LSPosed_2024-11-17T02_15_48.351576.zip](https://github.com/user-attachments/files/17790125/LSPosed_2024-11-17T02_15_48.351576.zip)

Settings: https://mega.nz/file/DFNRUIIA#PB1fl6ppcQPArrawzGSvXhbHmHCmsuGBMdRz2Q_iPvo

**Comment by binarynoise** [comment]
My hooks are applied and don't throw Exceptions, so :man_shrugging:.

Settings apk is obfuscated. There seems to be some additional logic similar to SystemUI, but I won't go deeper into that as it would be too brittle and too exhausting.

So all I can say is, I'm sorry, it won't work on OnePlus.
